### ISSUE TITLE
Ряды Фурье?

### ISSUE THREAD

**Issue by Wiki-fan** [agsh/mipt2017#1]
Добрый день.
Что в первом задании делают ряды Фурье? Там же везде должен быть Тейлор. В частности, возникают сложности с вычислением следующего члена ряда Фурье через предыдущий.
Лаба 1, варианты 26-28.

**Comment by NifantovaIrina** [comment]
В нулевой лабе?! Там вроде как надо было что-то с биномиальным
коэффициентами делать, не понимаю, о чем речь
А кроме нулевой я еще ничего не отправляла

12 апреля 2017 г., 22:37 пользователь Wiki-fan <notifications@github.com>
написал:

**Comment by agsh** [comment]
В таком случае можно отправлять без вычисления предыдущего
