### ISSUE TITLE
18 вариант Лабы, критерии поиска

### ISSUE THREAD

**Issue by ulyanin** [agsh/mipt2017#11]
Я пытаюсь отфильтровать юзеров, у которых есть блог, как те, у которых в ссылках в профиле (слева на странице) есть ссылка с href, содержащим social.msdn.microsoft.com.
Но вообще ничего не находится.

Такие юзеры вообще есть?

**Comment by agsh** [comment]
Брать всех, у кого есть следующий тэг `a` после тэга `svg` с классом `octicon-link`. Надеюсь, conduit с тэгом `svg` справится.
