### ISSUE TITLE
уточнение задания 17

### ISSUE THREAD

**Issue by AndreyPopovkin** [agsh/mipt2017#14]
Задание звучит так: "Какое количество разработчиков NuGet уже переехали на github, если судить по их никам?"

На первый взгляд человек в списке developers не так много и нет никакой проблемы поискать их руками (как и конечно же написать код, делающий это за меня). С другой стороны, поиск всех fillowers гораздо более серьезная задача, но тут проблема с получением всего их списка (а есть ли он вообще?).

Что в данном задании в итоге требуется?

**Comment by agsh** [comment]
Хм, за год их количество значительно уменьшилось.
Так что придётся трактовать задание в пользу сдающего. Распарсить страницу и просто поискать developer'ов
