### ISSUE TITLE
Lab2 haskell stringify

### ISSUE THREAD

**Issue by ulyanin** [agsh/mipt2017#4]
stringify :: Data.String.IsString t => JSON -> t
stringify = Data.String.fromString . show

Где insance show я определил выше

Это нормальная реализация stringify? Я не очень понимаю, что требуется в задании.

**Comment by agsh** [comment]
Да, нормальная. В задании просто предполагалось сначала написать эту функцию, а затем добавить JSON к классу типов Show с её помощью
