### ISSUE TITLE
Парсинг строк

### ISSUE THREAD

**Issue by eshlykov** [agsh/mipt2017#5]
Во второй лабе какие подстроки вида `"\\{что-то}"` необходимо заменять на один символ `'\{что-то}'`? Есть ли какой-то общий метод для обработки таких подстрок, где это необходимо?

**Comment by agsh** [comment]
Не очень понял вопрос, ведь когда мы экранируем с помощью backslash, то остаётся тот символ, что мы хотим, или перенос строки, или тот же backslash. Их немного, штук десять, найти можно в википедии
